name: CI - CV Generation

on:
  push:
    branches:
      - master  # Run on every push to the master branch
  pull_request:
    branches:
      - master  # Run on every pull request to the master branch

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # Define the OS matrix

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-basic
            hyperref
            microtype

      - name: Generate CV
        run: |
          ./run.sh

      - name: Upload CV PDF as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: cv-pdf-${{ matrix.os }}
          path: output/output.pdf
