name: Reusable workflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
        default: ubuntu-latest

jobs:
  build:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-basic
            microtype

      - name: Generate CV
        run: |
          ./run.sh

      - name: Upload CV PDF as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: cv-pdf-${{ inputs.os }}
          path: output/output.pdf
